### ISSUE TITLE
Offline for maintenance This app is undergoing maintenance right now.  Please check back later

### ISSUE THREAD

**Issue by MinouCrew** [FurryCoders/FurAffinity-API#1]
Hello, 
How are you ?
From this URL I received an error in the last 4 days
https://furaffinity-api.herokuapp.com/
503 Service Unavailable
Offline for maintenance This app is undergoing maintenance right now.  Please check back later
It is normal or the API stop working on furaffinity

**Comment by MatteoCampinoti94** [comment]
I am updating it to the newest version of FAAPI, it will be back online later today :)

**Comment by MinouCrew** [comment]
![89rkyl](https://github.com/FurryCoders/FurAffinity-API/assets/148549812/5359a05e-ac96-45f6-a0d5-b7957ef0c270)

**Comment by MatteoCampinoti94** [comment]
XDDD

Sorry! I forgot to push the changes x.x

It's building right now with the latest FAAPI library [v3.11.4](/FurryCoders/FAAPI) :)

**Comment by MatteoCampinoti94** [comment]
Version 1.5.2 is up and the API si back online :)

May I ask what you use the API for? :)

**Comment by MinouCrew** [comment]
No problem 😉 thank you
For a program that you give an artist name and he search his art on many website

**Comment by MinouCrew** [comment]
IM BACK ! 
WITH A BUG XD
For some art, i have an internal error (500)
Like for this link
https://furaffinity-api.herokuapp.com/submission/54766143/

The furaffinity link : https://www.furaffinity.net/view/54766143/

**Comment by MatteoCampinoti94** [comment]
It's fixed now :)

FastAPI changed a few things with how their response objects work, so now the app manually casts results to dicts before they are sent back :)
