### ISSUE TITLE
Error 401 Unauthorized

### ISSUE THREAD

**Issue by talopii** [FurryCoders/FurAffinity-API#2]
Good evening!

I would like to use your FurAffinity API to make some simple requests, but I am a bit confused on how to use it. As a test query, I've been trying to get my own account's user info. However, the server keeps responding with `401 Unauthorized`. I assume this is because I need to login to an account, but I have no idea how to do so. Could I have some tips on how to properly use this API?

Thank you!

Request URL: `https://furaffinity-api.herokuapp.com/user/talop/` (sent over `POST`)
- Request body
  ```
  {
    "cookies": [
      {
        "name": "string",
        "value": "string"
      }
    ],
    "bbcode": false
  }
  ```
Server response: 401 Unauthorized
- Response body
  ```
  { "detail": "System Message" }
  ```
- Response headers
  ```
  connection: keep-alive 
  content-length: 27 
  content-type: application/json 
  date: Mon,05 Feb 2024 20:44:33 GMT 
  nel: {"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]} 
  report-to: {"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1707165874&sid=812dcc77-0bd0-43b1-a5f1-b25750382959&s=dFxaQa0%2FOckzDcJkN64pb9tqT8LNAHAFy7gA5%2BON4DE%3D"}]} 
  reporting-endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1707165874&sid=812dcc77-0bd0-43b1-a5f1-b25750382959&s=dFxaQa0%2FOckzDcJkN64pb9tqT8LNAHAFy7gA5%2BON4DE%3D 
  server: uvicorn 
  via: 1.1 vegur 
  ```

**Comment by talopii** [comment]
Of course I find the answer to my problem right after opening the issue, ahaha. I didn't know that I needed the `a` and `b` cookies in my browser from FurAffinity in order to use the API. Sorry about that! For anyone else having the same issue, your request body should look something like this:
```
{
  "cookies": [
    { "name": "a", "value": "132d560f-e258-4fc6-8c86-6853adfd3a3a" },
    { "name": "b", "value": "e45a0816-a116-4718-b177-bf4b0e85c14a" }
  ],
  "bbcode": false
}
```
Where the `a` and `b` cookies come from your browser after logging in. After you log out, these cookies become invalid. I found my answer to this problem [here](https://github.com/FurryCoders/FAAPI/blob/main/README.md) under the "Cookies" section.

Leaving this issue open in case the repository maintainers have anything else to add before closing it 🦊

**Comment by MatteoCampinoti94** [comment]
Glad you found the solution, hope the API works well for you ^.^

**Comment by talopii** [comment]
It has so far, thank you!~ 🐱
