### ISSUE TITLE
Offline for maintenance This app is undergoing maintenance right now.  Please check back later.

### ISSUE THREAD

**Issue by AleksiLepaj** [FurryCoders/FurAffinity-API#4]
Hello,
I'm liek a very rookie programmer and would like to make API calls to this API through a program but it seems to be unavailable at the moment.
Maybe it's just bad timing on my side, but if it's not, is it normal?
Will it be back soon?

**Comment by MatteoCampinoti94** [comment]
It's back online now :)

I had disabled it while FA's domain was hijacked and forgot to turn it back on, my bad.

**Comment by AleksiLepaj** [comment]
Yippiee! Thank you!
